services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: ookayama_trap
    ports:
      - "3306:3306"
    volumes:
      - ./hono/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NS_MARIADB_HOSTNAME: db
      NS_MARIADB_PORT: 3306
      NS_MARIADB_USER: root
      NS_MARIADB_PASSWORD: password
      NS_MARIADB_DATABASE: ookayama_trap
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
